'use client';

import { useState, type ChangeEvent, type FormEvent } from 'react';
import { ArrowUpRight, ArrowRight, Check, ChevronDown, ChevronLeft, ChevronRight, Menu, X, CalendarDays, Users, Clock3, ShieldCheck, LayoutDashboard, SlidersHorizontal, Factory, Layers3, Cable, CircleHelp, Bell, Search, Plus, AlertTriangle, CheckCircle2, FileCheck2, Mail, Phone } from 'lucide-react';

const PHONE_DISPLAY = '06 17 10 95 86';
const PHONE_HREF = 'tel:+31617109586';

const features = [
  { icon: CalendarDays, title: 'Shift planning', text: 'Breng ploegencycli, wijzigingen en beschikbaarheid samen. Een rooster dat aansluit op de realiteit van de werkvloer.' },
  { icon: CalendarDays, title: 'Verlof & afwezigheid', text: 'Beoordeel aanvragen met de bezetting in beeld. Zie wat een vrije dag betekent voor de rest van de ploeg.' },
  { icon: Clock3, title: 'Overwerk inzichtelijk', text: 'Maak extra uren zichtbaar per medewerker en ploeg. Onderbouw beslissingen met overzicht in plaats van losse lijstjes.' },
  { icon: Users, title: 'Bezetting per shift', text: 'Zie waar mensen nodig zijn en welke ploeg ruimte heeft. Houd aandacht voor de shifts die om actie vragen.' },
  { icon: ShieldCheck, title: 'Skills & kwalificaties', text: 'Kijk verder dan het aantal mensen. Betrek de benodigde vaardigheden en geldigheid van kwalificaties bij je planning.' },
  { icon: LayoutDashboard, title: 'Overzicht voor elke rol', text: 'Een operationele blik die de supervisor werk uit handen neemt, en een centraal overzicht voor admins. De relevante informatie op één plek.' },
];
const faqs = [
  ['Voor welke organisaties is PetroShift bedoeld?', 'Voor industriële organisaties die met ploegen werken, zoals procesindustrie, energie, chemie, terminals en productie. De nadruk ligt op de samenhang tussen planning, bezetting en kwalificaties.'],
  ['Kan PetroShift aansluiten op ons ploegensysteem?', 'Je ploegencyclus, bezettingseisen en afspraken zijn het vertrekpunt. In een demo bespreken we hoe jouw situatie vertaald kan worden naar de inrichting van PetroShift. Specifieke roosterregels stemmen we vooraf af.'],
  ['Wat zien supervisors en admins?', 'De beoogde rolverdeling geeft supervisors inzicht in hun operationele planning en aanvragen. Admins krijgen een overkoepelend beeld en beheren de inrichting. De exacte toegang en verantwoordelijkheden stemmen we af op jouw organisatie.'],
  ['Is er al een koppeling met Workday?', 'Nee, er is geen live koppeling met Workday en gegevens worden niet automatisch uitgewisseld. PetroShift biedt wel een controlemoment: HR kan de gegevens uit PetroShift naast Workday leggen en afwijkingen signaleren. Een technische koppeling zou apart onderzocht en afgestemd moeten worden.'],
  ['Hoe zit het met security en persoonsgegevens?', 'Bij een implementatie moeten onder meer toegangsrechten, hosting, bewaartermijnen, logging en verwerkersafspraken worden vastgesteld. We bespreken deze vereisten vooraf met je IT- en privacyteam. Op deze pagina worden geen certificeringen of specifieke beveiligingsgaranties geclaimd.'],
  ['Hoe starten we en wat kost PetroShift?', 'We beginnen met een gesprek over je teams, processen en benodigde functionaliteit. Op basis daarvan kunnen scope, eventuele koppelingen, implementatie en prijs worden bepaald. Er worden op deze pagina geen vaste tarieven aangeboden.'],
];

function Logo({ small = false }: { small?: boolean }) { return <span className={`logo supplied-logo ${small ? 'small' : ''}`}><img src="/petroshift-logo.png" alt="PetroShift" width="1448" height="1086" /></span>; }

export default function Home() {
  const [menu, setMenu] = useState(false);
  const [view, setView] = useState('planning');
  const EMPTY_AANVRAAG = { naam: '', bedrijf: '', email: '', telefoon: '', bericht: '', website: '' };
  const [aanvraag, setAanvraag] = useState(EMPTY_AANVRAAG);
  const [status, setStatus] = useState<'idle' | 'sending' | 'sent' | 'error'>('idle');
  const demoUrl = (process.env.NEXT_PUBLIC_DEMO_URL || 'https://app.petroshift.nl').trim();
  const email = (process.env.NEXT_PUBLIC_CONTACT_EMAIL || 'info@petroshift.nl').trim();
  const bookingUrl = demoUrl && /^https:\/\//i.test(demoUrl) ? demoUrl : undefined;
  const contactEmail = (email && /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email) ? email : undefined) || 'info@petroshift.nl';
  const veld = (key: keyof typeof aanvraag) => ({
    value: aanvraag[key],
    onChange: (e: ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => setAanvraag({ ...aanvraag, [key]: e.target.value }),
  });
  const verstuurAanvraag = async (e: FormEvent) => {
    e.preventDefault();
    setStatus('sending');
    try {
      const res = await fetch('/api/aanvraag', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(aanvraag),
      });
      const data = await res.json().catch(() => ({ ok: false }));
      if (!res.ok || !data.ok) throw new Error(data.error || 'Versturen mislukt');
      setStatus('sent');
      setAanvraag(EMPTY_AANVRAAG);
    } catch {
      setStatus('error');
    }
  };
  return <>
    <a className="skip-link" href="#main">Direct naar inhoud</a>
    <header className="header"><div className="nav-wrap"><a href="#" aria-label="PetroShift homepage"><Logo/></a><nav className={menu?'nav open':'nav'} aria-label="Hoofdnavigatie" id="main-navigation">{[['Platform','#platform'],['Voor wie','#voor-wie'],['Integraties','#integraties'],['Veelgestelde vragen','#faq'],['Contact','#demo'],['Open de app','https://app.petroshift.nl']].map(([label,href])=><a key={href} href={href} onClick={()=>setMenu(false)}>{label}</a>)}</nav><a href={bookingUrl || "#demo"} className="button nav-cta">Bekijk de demo <ArrowUpRight size={17}/></a><button className="menu-toggle" aria-label={menu?'Menu sluiten':'Menu openen'} aria-expanded={menu} aria-controls="main-navigation" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div></header>
    <main id="main"><section className="hero"><div className="hero-grid" aria-hidden="true"/><div className="container hero-inner"><div className="eyebrow"><span className="tiny-line"/> BUILT FOR CONTINUOUS OPERATIONS</div><div className="hero-copy"><h1>Grip op elke<br/><span>ploegendienst.</span></h1><div className="hero-aside"><p>De juiste mensen. De juiste skills.<br/>Elke shift opnieuw.</p><p className="muted">Van planning en verlof tot bezetting en kwalificaties. Eén centraal overzicht voor teams die de operatie draaiende houden.</p><div className="hero-actions"><a href={bookingUrl || "#demo"} className="button">Probeer de demo <ArrowUpRight size={18}/></a><a href="#platform" className="text-link">Bekijk het platform <ArrowRight size={17}/></a></div></div></div>
    <div className="product-preview"><div className="preview-caption"><span><span className="orange-square"/> DE OPERATIE IN ÉÉN OVERZICHT</span><span>PRODUCTPREVIEW <span className="caption-separator">/</span> 01</span></div><a className="actual-app-preview" href="/petroshift-rooster.png" target="_blank" rel="noopener noreferrer" aria-label="Bekijk de volledige PetroShift-roosterscreenshot in een nieuw tabblad"><img src="/petroshift-rooster.png" alt="PetroShift-rooster: maandmatrix september 2026 met medewerkers, ochtend-, middag- en nachtdiensten, verlof, bezetting en tekorten." width="1655" height="1275" /><span>Bekijk op volledig formaat <ArrowUpRight size={16}/></span></a></div>
    <div className="hero-bottom"><span>Gemaakt voor een werkdag die nooit stopt.</span><div><span>24/7 OPERATIE</span><span>MEERDERE PLOEGEN</span><span>ÉÉN OVERZICHT</span></div></div></div></section>
    <section className="sector-strip" aria-label="Sectoren"><div className="container"><span>WAAR CONTINUÏTEIT TELT</span><div><span><Factory size={18}/> Procesindustrie</span><span><Layers3 size={18}/> Chemie & energie</span><span><Cable size={18}/> Terminals & logistiek</span><span><SlidersHorizontal size={18}/> Productie</span></div></div></section>
    <section className="section problem" id="oplossing"><div className="container problem-grid"><div><div className="eyebrow">01 / VAN COMPLEXITEIT NAAR CONTROLE</div><h2>De operatie draait door.<br/><span>Je planning moet mee.</span></h2><p className="section-intro">Een ziekmelding. Een verlofaanvraag. Een kwalificatie die verloopt. Eén wijziging kan de hele ploeg raken.</p></div><div className="problem-right"><p>Als je planning verspreid staat over spreadsheets, berichten en losse systemen, ontbreekt het totaalbeeld. PetroShift brengt de informatie bij elkaar die je nodig hebt om te handelen.</p><div className="before-after"><div><span className="before-label">VERSNIPPERD</span><span>Roosters in spreadsheets</span><span>Verlof via losse berichten</span><span>Skills in aparte overzichten</span></div><ArrowRight size={22}/><div><span className="after-label">VERBONDEN</span><span><Check size={16}/> Eén actueel planningsbeeld</span><span><Check size={16}/> Aanvragen in context</span><span><Check size={16}/> Mensen én kwalificaties</span></div></div></div></div></section>
    <section className="section platform" id="platform"><div className="container"><div className="section-head"><div><div className="eyebrow">02 / HET PLATFORM</div><h2>Alles rond je ploeg.<br/><span>Niets tussen wal en schip.</span></h2></div><p>Van de eerste roosterwijziging tot het totaalbeeld voor de supervisor. Meer samenhang in elke beslissing.</p></div><div className="features">{features.map(({icon:Icon,title,text},i)=><article className="feature" key={title}><div className="feature-top"><Icon size={23} strokeWidth={1.6}/><span>0{i+1}</span></div><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
    <section className="section showcase"><div className="container showcase-grid"><div className="showcase-copy"><div className="eyebrow">03 / VAN INZICHT NAAR ACTIE</div><h2>Zie wat speelt.<br/><span>Weet waar je nodig bent.</span></h2><p>Een goede planning gaat verder dan een gevuld rooster. Breng beschikbaarheid, bezetting en skills samen voordat de volgende shift begint.</p><div className="view-options" aria-label="Kies een productvoorbeeld">{[{id:'planning',n:'01',title:'Plan met overzicht',text:'Een herkenbaar ritme voor elke ploeg.'},{id:'bezetting',n:'02',title:'Zie gaten in de bezetting',text:'Geef aandacht aan de juiste shift.'},{id:'skills',n:'03',title:'Kijk verder dan aantallen',text:'Neem de juiste kwalificaties mee.'}].map(t=><button aria-pressed={view===t.id} className={view===t.id?'active':''} key={t.id} onClick={()=>setView(t.id)}><span>{t.n}</span><div><strong>{t.title}</strong><small>{t.text}</small></div><ArrowUpRight size={18}/></button>)}</div></div><div className="focus-mockup"><div className="mockup-top"><Logo small/><span>SUPERVISOR VIEW</span></div><span className="mini-eyebrow">{view==='planning'?'AANVRAGEN':view==='bezetting'?'BEZETTING':'KWALIFICATIES'} / VANDAAG</span><h3>{view==='planning'?'Verlof met het hele plaatje.':view==='bezetting'?'De volgende shift, voorbereid.':'Maak skills onderdeel van je plan.'}</h3><div className="request-card"><div className="request-person"><span className="person-avatar a1">SB</span><div><strong>{view==='planning'?'Sanne Bakker':view==='bezetting'?'Ploeg B · Late dienst':'Werken op hoogte'}</strong><small>{view==='planning'?'Field operator · Ploeg B':view==='bezetting'?'14:00 – 22:00 · Plant Rotterdam':'Kwalificatieoverzicht · Plant Rotterdam'}</small></div><span className="pending">{view==='planning'?'In afwachting':'Aandacht'}</span></div><div className="request-data"><span>{view==='planning'?'Aangevraagd verlof':view==='bezetting'?'Gepland / benodigd':'Binnenkort verlopen'}<strong>{view==='planning'?'18 september 2026':view==='bezetting'?'13 / 14 medewerkers':'2 kwalificaties'}</strong></span><CalendarDays size={24}/></div><div className="check-line"><CheckCircle2 size={17}/><span>{view==='skills'?'18 medewerkers gekwalificeerd':'Beschikbaarheid in beeld'}</span></div><div className="check-line"><CheckCircle2 size={17}/><span>{view==='skills'?'Geldigheid per medewerker':'Skills van de ploeg inzichtelijk'}</span></div><div className="review-note"><AlertTriangle size={17}/><span>{view==='planning'?'Bekijk de impact op de late dienst vóór goedkeuring.':view==='bezetting'?'Controleer vervanging voor de open positie.':'Plan tijdig een beoordeling of hercertificering.'}</span></div></div><div className="mockup-foot"><span className="orange-square"/> INZICHT VÓÓR JE BESLIST <span>Illustratieve productmockup</span></div></div></div></section>
    <section className="section audience" id="voor-wie"><div className="container"><div className="section-head"><div><div className="eyebrow">04 / VOOR DE MENSEN ACHTER DE OPERATIE</div><h2>Dezelfde operatie.<br/><span>Ieder zijn eigen overzicht.</span></h2></div><p>Van de werkvloer tot het centrale beheer. Met informatie die past bij de verantwoordelijkheid.</p></div><div className="roles">{[{n:'01',role:'Supervisors',title:'Rust in de dagelijkse operatie.',text:'Overzie de ploeg, beoordeel aanvragen en houd grip op wijzigingen voordat de dienst begint — minder handmatig uitzoekwerk, meer tijd voor de ploeg.',tags:'Ploegoverzicht / Aanvragen / Bezetting / Minder werkdruk'},{n:'02',role:'Planners & operations',title:'Vooruitkijken met het hele beeld.',text:'Breng roosters, beschikbaarheid en skills samen. Herken knelpunten en stem de planning af over ploegen heen.',tags:'Shift planning / Capaciteit / Skills'},{n:'03',role:'Admins & HR',title:'Samenhang in het beheer.',text:'Verbind de operationele behoefte met medewerkersgegevens, rollen en een consistente inrichting.',tags:'Beheer / Rollen / HR-afstemming'}].map(r=><article key={r.n}><span className="role-num">{r.n}</span><span className="role-label">{r.role}</span><h3>{r.title}</h3><p>{r.text}</p><div>{r.tags}</div></article>)}</div></div></section>
    <section className="founder-strip" aria-label="Over de oprichter"><div className="container founder-strip-inner"><img src="/jurrien-bolland.jpg" alt="Jurrien Bolland, oprichter en eigenaar van PetroShift" width="96" height="96"/><div><span className="founder-role">OPRICHTER & EIGENAAR</span><h3>Jurrien Bolland</h3><p>Rechtstreeks contact met wie PetroShift bouwt — geen callcenter tussen jou en de antwoorden.</p></div></div></section>
    <section className="section integrations" id="integraties"><div className="container integration-grid"><div><div className="eyebrow">05 / PASSEND IN JOUW LANDSCHAP</div><h2>De werkvloer en HR.<br/><span>Beter verbonden.</span></h2><p className="section-intro">Je planning staat niet op zichzelf. We bespreken hoe PetroShift kan aansluiten op je bestaande processen en systemen.</p><div className="security-note"><ShieldCheck size={24}/><div><h3>Security als implementatievoorwaarde</h3><p>Toegang, gegevensverwerking en beheer stemmen we vooraf af met je IT- en privacyteam.</p></div></div></div><div className="integration-card"><div className="connection"><Logo small/><FileCheck2 size={26}/><span className="workday">workday<span/></span></div><div className="status-outline">GEEN LIVE KOPPELING</div><h3>Workday-controle voor HR</h3><p>PetroShift wisselt geen gegevens automatisch uit met Workday. In plaats daarvan is het een controlemoment: HR legt de bezetting en uren uit PetroShift naast Workday en signaleert afwijkingen, zonder technische koppeling.</p><div className="integration-foot"><CircleHelp size={16}/> Handmatige controle, geen automatische synchronisatie</div></div></div></section>
    <section className="section faq" id="faq"><div className="container faq-grid"><div><div className="eyebrow">06 / GOED OM TE WETEN</div><h2>Heldere vragen.<br/><span>Heldere antwoorden.</span></h2><p>Een andere vraag? Neem die mee in het gesprek over jouw operatie.</p><a href={bookingUrl || "#demo"} className="text-link">Laten we kennismaken <ArrowUpRight size={18}/></a></div><div className="faq-list">{faqs.map(([q,a])=><details key={q}><summary>{q}<Plus size={19}/></summary><p>{a}</p></details>)}</div></div></section>
    <section className="demo-section" id="demo"><div className="container demo-grid"><div><div className="eyebrow">DE VOLGENDE SHIFT BEGINT MET OVERZICHT</div><h2>Klaar voor meer grip<br/>op jouw operatie?</h2><p>Bekijk hoe PetroShift kan aansluiten op jouw ploegen, processen en dagelijkse praktijk.</p><div className="contact-methods"><a href={PHONE_HREF}><Phone size={18}/> {PHONE_DISPLAY}</a><a href={`mailto:${contactEmail}`}><Mail size={18}/> {contactEmail}</a></div><div className="demo-checks"><span><Check size={16}/> Jouw ploegensysteem centraal</span><span><Check size={16}/> Ruimte voor inhoudelijke vragen</span></div>{bookingUrl && <a className="button button-dark" href={bookingUrl} target="_blank" rel="noopener noreferrer" style={{marginTop:24}}>Bekijk de demo <ArrowUpRight size={20}/></a>}</div><form className="aanvraag-form" onSubmit={verstuurAanvraag} aria-label="Aanvraagformulier">{status==='sent'?<><h3>Aanvraag verstuurd</h3><p className="form-hint">Bedankt — we nemen zo snel mogelijk contact op.</p></>:<><h3>Vraag vrijblijvend informatie aan</h3><p className="form-hint">We nemen zo snel mogelijk contact op.</p>{status==='error'&&<p className="form-error">Dat ging niet goed. Bel of mail ons direct: <a href={PHONE_HREF}>{PHONE_DISPLAY}</a> of <a href={`mailto:${contactEmail}`}>{contactEmail}</a>.</p>}<div className="field-row"><label>Naam*<input required {...veld('naam')} autoComplete="name"/></label><label>Bedrijf<input {...veld('bedrijf')} autoComplete="organization"/></label></div><div className="field-row"><label>E-mail*<input required type="email" {...veld('email')} autoComplete="email"/></label><label>Telefoonnummer<input type="tel" {...veld('telefoon')} autoComplete="tel" placeholder="06 12 34 56 78"/></label></div><label>Bericht<textarea rows={4} {...veld('bericht')} placeholder="Vertel kort over je ploegen en waar je hulp bij zoekt."/></label><input className="hp-field" tabIndex={-1} aria-hidden="true" autoComplete="off" {...veld('website')}/><button type="submit" className="button button-dark" disabled={status==='sending'}>{status==='sending'?'Bezig met versturen…':<>Verstuur aanvraag <ArrowUpRight size={18}/></>}</button></>}</form></div></section>
    </main><footer><div className="container footer-main"><a href="#" aria-label="PetroShift bovenaan"><Logo/></a><p>Built for the people<br/>who keep operations running.</p><a href="#platform">Platform</a><a href="#integraties">Integraties & security</a><a href={bookingUrl || "#demo"}>Demo</a><a href="https://app.petroshift.nl">Open de app</a><a href={`mailto:${contactEmail}`}>{contactEmail}</a><a className="footer-phone" href={PHONE_HREF}>{PHONE_DISPLAY}</a></div><div className="container footer-bottom"><span>© {new Date().getFullYear()} PetroShift</span><span>Roosterscreenshot uit de app; overige voorbeelden zijn illustratief.</span><span>CONTINUITY, PLANNED.</span></div></footer>
  </>;
}
