'use client';

import { useState } from 'react';
import RoosterPreview from '../components/RoosterPreview';
import AanvraagForm from '../components/AanvraagForm';
import { ArrowUpRight, ArrowRight, Check, CalendarDays, Users, Clock3, ShieldCheck, LayoutDashboard, LayoutGrid, ArrowLeftRight, UserPlus, Download, SlidersHorizontal, Factory, Layers3, Cable, CircleHelp, Bell, Plus, AlertTriangle, CheckCircle2, FileCheck2, Mail, Phone, Menu, X } from 'lucide-react';

const PHONE_DISPLAY = '06 17 10 95 86';
const PHONE_HREF = 'tel:+31617109586';

const features = [
  { icon: CalendarDays, title: 'Shift planning', text: 'Every shift pattern — not just 2-2-2 — including on-call days. Bring cycles, changes and availability together in one roster that matches the reality of the shop floor.' },
  { icon: CalendarDays, title: 'Leave & absence', text: 'Review requests with staffing in view. See what a day off means for the rest of the team.' },
  { icon: Clock3, title: 'Overtime made visible', text: 'Make extra hours visible per employee and team. Base decisions on overview instead of loose lists.' },
  { icon: Users, title: 'Staffing per shift', text: 'See where people are needed and which team has room. Focus attention on the shifts that need it.' },
  { icon: ShieldCheck, title: 'Skills & qualifications', text: 'Look beyond headcount. Factor in the required skills and the validity of qualifications in your planning.' },
  { icon: LayoutGrid, title: 'Positioning per shift', text: 'Assign people to the right installation and position for each shift — with an automatic suggestion that fills as many positions as possible.' },
  { icon: ArrowLeftRight, title: 'Swaps & team transfers', text: 'From a one-off swap between two shifts to a permanent move to another team — always with approval and without gaps in the roster.' },
  { icon: UserPlus, title: 'Arrange replacements', text: 'Invite a replacement for an open shift and let them confirm or decline themselves — no more phoning around.' },
  { icon: LayoutDashboard, title: 'One view per role', text: 'An operational view that takes work off the supervisor’s hands, and a central overview for admins. The relevant information in one place, with configurable permissions per role.' },
];
const faqs = [
  ['Which organizations is PetroShift for?', 'For industrial organizations that work with shift teams, such as process industry, energy, chemicals, terminals and manufacturing. The focus is on the coherence between planning, staffing and qualifications.'],
  ['Can PetroShift fit our shift system?', 'Yes. PetroShift isn’t locked into one pattern like 2-2-2 — any shift pattern (for example 4- or 5-team shift systems, or your own cycle) can be set up, including on-call days. Your shift cycle, staffing requirements and agreements are the starting point; in a demo we discuss how your situation translates into PetroShift’s setup.'],
  ['What do supervisors and admins see?', 'The intended role split gives supervisors insight into their operational planning and requests. Admins get an overarching view and manage the setup. We align the exact access and responsibilities with your organization.'],
  ['Is there already an integration with Workday?', 'No, there is no live integration with Workday and data isn’t exchanged automatically. PetroShift does offer a reconciliation step: HR can compare data from PetroShift against Workday and flag discrepancies. A technical integration would need to be researched and agreed on separately.'],
  ['What about security and personal data?', 'An implementation requires establishing access rights, hosting, retention periods, logging and data processing agreements, among other things. We discuss these requirements with your IT and privacy team beforehand. This page does not claim any certifications or specific security guarantees.'],
  ['How do we get started, and what does PetroShift cost?', 'We start with a conversation about your teams, processes and required functionality. Based on that, scope, any integrations, implementation and price can be determined. This page does not offer fixed rates.'],
];

const steps = [
  ['Set up your teams', 'Choose your shift pattern, staffing requirements, roles and skills. Sector templates give you a workable starting point that you adjust yourself.'],
  ['Plan and staff', 'The roster is calculated from your pattern. The matrix shows staffing, the minimum, leave and shortages per day.'],
  ['Handle changes', 'Leave, swaps, replacements and cover run through requests with approval, with rest-time checks.'],
  ['Keep the overview', 'Dashboard, notifications and reports per role, plus a calendar feed so employees see their shifts in their own calendar.'],
];

const spotlight = [
  { img: '/feature-indeling.png', w: 1600, h: 1290, title: 'Assignment per position', text: 'Fill in the whole run of shifts on one screen. Assign people to unit and position per shift, with stars for the qualification level and an automatic suggestion that fills as many positions as possible.', alt: 'Assignment: run of shifts with the positions PTL, deputy supervisor and units per shift, filled with employees and stars for qualification level.' },
  { img: '/feature-vakantierooster.png', w: 1600, h: 1215, title: 'Holiday roster', text: 'Analyse in one go whether staffing holds for a whole holiday period. Where it gets tight, PetroShift proposes cover and shift swaps, and the calendar shows per employee what is in draft.', alt: 'Holiday roster: calendar per employee with shifts, leave and on-call days, and the message that 0 of 189 shifts have a shortage.' },
  { img: '/feature-stop.png', w: 1600, h: 1276, title: 'Shutdowns and events', text: 'Plan a company-wide shutdown per day in a familiar matrix, with participants from all teams and a rest check on every assignment. Afterwards you process the hours worked as overtime.', alt: 'Shutdown planning: matrix of participants and days with day shift, morning and afternoon.' },
  { img: '/feature-assistent.png', w: 1400, h: 1083, title: 'AI assistant for supervisors', text: 'Ask in plain language, such as “Who can cover tomorrow afternoon?”. The assistant looks through the roster, checks rest, leave and qualifications, and never changes anything itself. Optional per company.', alt: 'The assistant answers who can cover tomorrow afternoon with a list of suitable employees.' },
];
const news = [
  { title: 'Planning and staffing', items: [
    { t: 'Holiday roster', d: 'Analyse staffing per holiday period and let PetroShift propose cover and shift swaps. With automatic fill and progress, a fairness overview per person and re-planning after publishing.', n: true },
    { t: 'Shutdowns and events', d: 'Plan a company-wide shutdown per day in a familiar matrix, with rest checks. Record worked hours per participant and process them as overtime.', n: true },
    { t: 'Cover and open shifts', d: 'When short-staffed, find cover from the roster in a ranked list based on availability, rest time and overtime hours. Employees apply for an open shift and the supervisor approves.' },
    { t: 'Qualification levels 1 to 4', d: 'From shadowing to senior, including the deputy supervisor slot. A shadowing employee counts as an extra person and does not cover a position.', n: true },
    { t: 'Rest-time checks where you plan', d: 'The working-time rules apply in the roster, the holiday roster and shutdown planning. When swapping, PetroShift makes sure the colleague’s shift stays covered.', n: true },
    { t: 'Public holidays', d: 'Official Dutch public holidays appear in the roster and holidays worked are counted per employee.' },
    { t: 'Smart roster matrix', d: 'Today’s column clearly highlighted, cell comments like in Excel, a separate window and keyboard control.', n: true },
  ] },
  { title: 'Requests and employees', items: [
    { t: 'One list for requests', d: 'Everything waiting for a supervisor, sorted by date, with filters per type: leave, replacement, swap or team change.', n: true },
    { t: 'Leave balance in hours', d: 'Employees enter their current Workday balance and PetroShift calculates the annual total in hours.' },
    { t: 'My overview', d: 'Upcoming shifts, leave and on-call meters, holidays worked and who relieves you.' },
    { t: 'Notifications and calendar', d: 'Notifications per category via push, WhatsApp or email, and a personal calendar feed for Apple, Outlook or Google.' },
  ] },
  { title: 'Insight and help', items: [
    { t: 'Reports and automation in numbers', d: 'Reports on absence, leave, overtime and staffing with CSV export. The KPI dashboard also shows how many holiday and shutdown shifts were planned automatically.', n: true },
    { t: 'AI assistant for supervisors', d: 'Optional and read-only: ask about employees, cover, rest times and a day’s staffing.', n: true },
    { t: 'Report a problem in the app', d: 'Employees report an issue directly with a selection on the screen.' },
  ] },
  { title: 'Setup and administration', items: [
    { t: 'Onboarding with sector templates', d: 'A wizard with a workable starting point for roster, staffing, roles and skills, which you adjust yourself.' },
    { t: 'Modules per company', d: 'Switch on only what you need. The roster itself is the foundation.' },
    { t: 'Roles and permissions', d: 'Operator, supervisor, deputy supervisor, department and company admin, with configurable permissions and a dedicated view per role.' },
    { t: 'Audit log and separated data', d: 'Changes are recorded and each company works with its own data.' },
  ] },
  { title: 'Access and privacy', items: [
    { t: 'Two-step verification', d: 'Optional, with backup codes and rate-limited sign-in attempts.', n: true },
    { t: 'Sign in with Microsoft', d: 'Entra ID (OpenID Connect) is available on request, for existing accounts only.', n: true },
    { t: 'Manage your own data', d: 'Employees export their own data and can have their account deleted (GDPR).', n: true },
    { t: 'Install as an app', d: 'Shortcuts to roster, requests and notifications, with install help for Android and iPhone.', n: true },
  ] },
];

function Logo({ small = false }: { small?: boolean }) { return <span className={`logo supplied-logo ${small ? 'small' : ''}`}><img src="/petroshift-logo.png" alt="PetroShift" width="440" height="378" /></span>; }
function HeaderLogo() { return <img src="/petroshift-logo-header.png" alt="PetroShift" className="header-logo" width="532" height="200" />; }

export default function Home() {
  const [menu, setMenu] = useState(false);
  const [view, setView] = useState('planning');
  const demoUrl = (process.env.NEXT_PUBLIC_DEMO_URL || 'https://app.petroshift.nl').trim();
  const email = (process.env.NEXT_PUBLIC_CONTACT_EMAIL || 'info@petroshift.nl').trim();
  const bookingUrl = demoUrl && /^https:\/\//i.test(demoUrl) ? demoUrl : undefined;
  const contactEmail = (email && /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email) ? email : undefined) || 'info@petroshift.nl';
  return <>
    <a className="skip-link" href="#main">Skip to content</a>
    <header className="header"><div className="nav-wrap"><a href="#" aria-label="PetroShift homepage"><HeaderLogo/></a><nav className={menu?'nav open':'nav'} aria-label="Main navigation" id="main-navigation">{[['Platform','#platform'],['Who it’s for','#who'],['Integrations','#integrations'],['FAQ','#faq'],['Contact','#demo'],['Open the app','https://app.petroshift.nl']].map(([label,href])=><a key={href} href={href} onClick={()=>setMenu(false)}>{label}</a>)}<a href="/" className="lang-switch">NL</a></nav><a href={bookingUrl || "#demo"} className="button nav-cta">View the demo <ArrowUpRight size={17}/></a><button className="menu-toggle" aria-label={menu?'Close menu':'Open menu'} aria-expanded={menu} aria-controls="main-navigation" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div></header>
    <main id="main"><section className="hero"><div className="hero-grid" aria-hidden="true"/><div className="container hero-inner"><div className="eyebrow"><span className="tiny-line"/> BUILT FOR CONTINUOUS OPERATIONS</div><div className="hero-copy"><h1>Grip on every<br/><span>shift.</span></h1><div className="hero-aside"><p>The right people. The right skills.<br/>Every shift, again.</p><p className="muted">From planning and leave to staffing and qualifications. One central overview for teams that keep operations running.</p><div className="hero-actions"><a href={bookingUrl || "#demo"} className="button">Try the demo <ArrowUpRight size={18}/></a><a href="#platform" className="text-link">View the platform <ArrowRight size={17}/></a></div></div></div>
    <div className="product-preview"><div className="preview-caption"><span><span className="orange-square"/> THE OPERATION IN ONE VIEW</span><span>PRODUCT PREVIEW <span className="caption-separator">/</span> 01</span></div><RoosterPreview locale="en"/><p className="preview-note">This example shows a 5-team 2-2-2 roster — other shift patterns and on-call days are supported just as well.</p></div>
    <div className="hero-bottom"><span>Built for a workday that never stops.</span><div><span>24/7 OPERATIONS</span><span>MULTIPLE TEAMS</span><span>ONE OVERVIEW</span><span>APP COMING SOON TO APP STORE & GOOGLE PLAY</span></div></div></div></section>
    <section className="sector-strip" aria-label="Sectors"><div className="container"><span>WHERE CONTINUITY MATTERS</span><div><span><Factory size={18}/> Process industry</span><span><Layers3 size={18}/> Chemicals & energy</span><span><Cable size={18}/> Terminals & logistics</span><span><SlidersHorizontal size={18}/> Manufacturing</span></div></div></section>
    <section className="section problem" id="solution"><div className="container problem-grid"><div><div className="eyebrow">01 / FROM COMPLEXITY TO CONTROL</div><h2>Operations don’t stop.<br/><span>Your planning has to keep up.</span></h2><p className="section-intro">A sick day. A leave request. An expiring qualification. One change can affect the whole team.</p></div><div className="problem-right"><p>When your planning is spread across spreadsheets, messages and separate systems, you lose the full picture. PetroShift brings together the information you need to act.</p><div className="before-after"><div><span className="before-label">FRAGMENTED</span><span>Rosters in spreadsheets</span><span>Leave via separate messages</span><span>Skills in separate overviews</span></div><ArrowRight size={22}/><div><span className="after-label">CONNECTED</span><span><Check size={16}/> One up-to-date planning view</span><span><Check size={16}/> Requests in context</span><span><Check size={16}/> People and qualifications</span></div></div></div></div></section>
    <section className="section platform" id="platform"><div className="container"><div className="section-head"><div><div className="eyebrow">02 / THE PLATFORM</div><h2>Everything around your team.<br/><span>Nothing falls through the cracks.</span></h2></div><p>From the first roster change to the full picture for the supervisor. More coherence in every decision.</p></div><div className="features">{features.map(({icon:Icon,title,text},i)=><article className="feature" key={title}><div className="feature-top"><Icon size={23} strokeWidth={1.6}/><span>0{i+1}</span></div><h3>{title}</h3><p>{text}</p></article>)}</div><div className="how"><div className="eyebrow">HOW IT WORKS</div><ol>{steps.map(([t,d],i)=><li key={t}><span className="how-n">0{i+1}</span><h3>{t}</h3><p>{d}</p></li>)}</ol></div><div className="spotlight"><div className="eyebrow">IN PICTURES</div><h3 className="news-title">Four features up close</h3>{spotlight.map(s=><article className="spot" key={s.title}><div className="spot-text"><h4>{s.title}</h4><p>{s.text}</p></div><a className="spot-shot" href={s.img} target="_blank" rel="noopener noreferrer"><img src={s.img} alt={s.alt} width={s.w} height={s.h} loading="lazy" /></a></article>)}</div><div className="news"><div className="eyebrow">MORE ABOUT PETROSHIFT</div><h3 className="news-title">Everything else you get</h3><div className="news-grid">{news.map(g=><section key={g.title}><h4>{g.title}</h4><dl>{g.items.map(({t,d,n})=><div key={t}><dt>{t}{n&&<em className="new-tag">New</em>}</dt><dd>{d}</dd></div>)}</dl></section>)}</div></div><p className="notif-note"><Bell size={16}/> Automatic notifications via WhatsApp, push (in the app) or email — configurable per employee.</p><p className="notif-note"><Download size={16}/> Reports on absence, leave, overtime and staffing, with CSV export for Excel.</p></div></section>
    <section className="section showcase"><div className="container showcase-grid"><div className="showcase-copy"><div className="eyebrow">03 / FROM INSIGHT TO ACTION</div><h2>See what’s happening.<br/><span>Know where you’re needed.</span></h2><p>Good planning goes beyond a filled roster. Bring availability, staffing and skills together before the next shift starts.</p><div className="view-options" aria-label="Choose a product example">{[{id:'planning',n:'01',title:'Plan with an overview',text:'A recognizable rhythm for every team.'},{id:'bezetting',n:'02',title:'See staffing gaps',text:'Focus on the shift that needs it.'},{id:'skills',n:'03',title:'Look beyond headcount',text:'Factor in the right qualifications.'}].map(t=><button aria-pressed={view===t.id} className={view===t.id?'active':''} key={t.id} onClick={()=>setView(t.id)}><span>{t.n}</span><div><strong>{t.title}</strong><small>{t.text}</small></div><ArrowUpRight size={18}/></button>)}</div></div><div className="focus-mockup"><div className="mockup-top"><Logo small/><span>SUPERVISOR VIEW</span></div><span className="mini-eyebrow">{view==='planning'?'REQUESTS':view==='bezetting'?'STAFFING':'QUALIFICATIONS'} / TODAY</span><h3>{view==='planning'?'Leave, with the full picture.':view==='bezetting'?'The next shift, prepared.':'Make skills part of your plan.'}</h3><div className="request-card"><div className="request-person"><span className="person-avatar a1">SB</span><div><strong>{view==='planning'?'Sanne Bakker':view==='bezetting'?'Team B · Late shift':'Working at height'}</strong><small>{view==='planning'?'Field operator · Team B':view==='bezetting'?'14:00 – 22:00 · Plant Rotterdam':'Qualification overview · Plant Rotterdam'}</small></div><span className="pending">{view==='planning'?'Pending':'Needs attention'}</span></div><div className="request-data"><span>{view==='planning'?'Requested leave':view==='bezetting'?'Scheduled / required':'Expiring soon'}<strong>{view==='planning'?'September 18, 2026':view==='bezetting'?'13 / 14 employees':'2 qualifications'}</strong></span><CalendarDays size={24}/></div><div className="check-line"><CheckCircle2 size={17}/><span>{view==='skills'?'18 employees qualified':'Availability in view'}</span></div><div className="check-line"><CheckCircle2 size={17}/><span>{view==='skills'?'Validity per employee':'Team skills visible'}</span></div><div className="review-note"><AlertTriangle size={17}/><span>{view==='planning'?'Check the impact on the late shift before approving.':view==='bezetting'?'Check replacement for the open position.':'Schedule a review or recertification in time.'}</span></div></div><div className="mockup-foot"><span className="orange-square"/> INSIGHT BEFORE YOU DECIDE <span>Illustrative product mockup</span></div></div></div></section>
    <section className="section audience" id="who"><div className="container"><div className="section-head"><div><div className="eyebrow">04 / FOR THE PEOPLE BEHIND THE OPERATION</div><h2>Same operation.<br/><span>Each their own view.</span></h2></div><p>From the shop floor to central management. With information that matches the responsibility.</p></div><div className="roles">{[{n:'01',role:'Supervisors',title:'Calm in day-to-day operations.',text:'Oversee the team, review requests and stay on top of changes before the shift starts — less manual digging, more time for the team.',tags:'Team overview / Requests / Staffing / Less workload'},{n:'02',role:'Planners & operations',title:'Looking ahead with the full picture.',text:'Bring rosters, availability and skills together. Spot bottlenecks and align planning across teams.',tags:'Shift planning / Capacity / Skills'},{n:'03',role:'Admins & HR',title:'Coherence in management.',text:'Connect operational needs with employee data, roles and a consistent setup.',tags:'Management / Roles / HR alignment'}].map(r=><article key={r.n}><span className="role-num">{r.n}</span><span className="role-label">{r.role}</span><h3>{r.title}</h3><p>{r.text}</p><div>{r.tags}</div></article>)}</div></div></section>
    <section className="founder-strip" aria-label="About the founder"><div className="container founder-strip-inner"><img src="/jurrien-bolland.jpg" alt="Jurrien Bolland, founder and owner of PetroShift" width="96" height="96"/><div><span className="founder-role">FOUNDER & OWNER</span><h3>Jurrien Bolland</h3><p>Direct contact with the person building PetroShift — no call center between you and the answers.</p></div></div></section>
    <section className="section integrations" id="integrations"><div className="container integration-grid"><div><div className="eyebrow">05 / FITTING YOUR LANDSCAPE</div><h2>The shop floor and HR.<br/><span>Better connected.</span></h2><p className="section-intro">Your planning doesn’t stand alone. We discuss how PetroShift can connect with your existing processes and systems.</p><div className="security-note"><ShieldCheck size={24}/><div><h3>Security as an implementation requirement</h3><p>We align access, data processing and management with your IT and privacy team beforehand.</p></div></div></div><div className="integration-card"><div className="connection"><Logo small/><FileCheck2 size={26}/><span className="workday">workday<span/></span></div><div className="status-outline">NO LIVE INTEGRATION</div><h3>Workday check for HR</h3><p>PetroShift doesn’t exchange data with Workday automatically. Instead, it’s a reconciliation step: HR compares staffing and hours from PetroShift against Workday and flags discrepancies, without a technical integration.</p><div className="integration-foot"><CircleHelp size={16}/> Manual check, no automatic sync</div></div></div></section>
    <section className="section faq" id="faq"><div className="container faq-grid"><div><div className="eyebrow">06 / GOOD TO KNOW</div><h2>Clear questions.<br/><span>Clear answers.</span></h2><p>A different question? Bring it into the conversation about your operation.</p><a href={bookingUrl || "#demo"} className="text-link">Let’s talk <ArrowUpRight size={18}/></a></div><div className="faq-list">{faqs.map(([q,a])=><details key={q}><summary>{q}<Plus size={19}/></summary><p>{a}</p></details>)}</div></div></section>
    <section className="demo-section" id="demo"><div className="container demo-grid"><div><div className="eyebrow">THE NEXT SHIFT STARTS WITH AN OVERVIEW</div><h2>Ready for more grip<br/>on your operation?</h2><p>See how PetroShift can fit your teams, processes and daily practice.</p><div className="contact-methods"><a href={PHONE_HREF}><Phone size={18}/> {PHONE_DISPLAY}</a><a href={`mailto:${contactEmail}`}><Mail size={18}/> {contactEmail}</a></div><div className="demo-checks"><span><Check size={16}/> Your shift system at the center</span><span><Check size={16}/> Room for in-depth questions</span></div>{bookingUrl && <a className="button button-dark" href={bookingUrl} target="_blank" rel="noopener noreferrer" style={{marginTop:24}}>View the demo <ArrowUpRight size={20}/></a>}</div><AanvraagForm locale="en" phoneDisplay={PHONE_DISPLAY} phoneHref={PHONE_HREF} contactEmail={contactEmail}/></div></section>
    </main><footer><div className="container footer-main"><a href="#" aria-label="PetroShift top"><Logo/></a><p>Built for the people<br/>who keep operations running.</p><a href="#platform">Platform</a><a href="#integrations">Integrations & security</a><a href={bookingUrl || "#demo"}>Demo</a><a href="https://app.petroshift.nl">Open the app</a><a href="/en/privacy">Privacy</a><a href={`mailto:${contactEmail}`}>{contactEmail}</a><a className="footer-phone" href={PHONE_HREF}>{PHONE_DISPLAY}</a></div><div className="container footer-bottom"><span>© {new Date().getFullYear()} PetroShift</span><span>Screenshots from the app with demo data; other examples are illustrative.</span><span>CONTINUITY, PLANNED.</span></div></footer>
  </>;
}
