'use client';

import { useState, type ChangeEvent, type FormEvent } from 'react';
import { ArrowUpRight, ArrowRight, Check, CalendarDays, Users, Clock3, ShieldCheck, LayoutDashboard, LayoutGrid, ArrowLeftRight, UserPlus, Download, SlidersHorizontal, Factory, Layers3, Cable, CircleHelp, Bell, Plus, AlertTriangle, CheckCircle2, FileCheck2, Mail, Phone, Menu, X } from 'lucide-react';

const PHONE_DISPLAY = '06 17 10 95 86';
const PHONE_HREF = 'tel:+31617109586';

const features = [
  { icon: CalendarDays, title: 'Shift planning', text: 'Every shift pattern — not just 2-2-2 — including on-call days. Bring cycles, changes and availability together in one roster that matches the reality of the shop floor.' },
  { icon: CalendarDays, title: 'Leave & absence', text: 'Review requests with staffing in view. See what a day off means for the rest of the team.' },
  { icon: Clock3, title: 'Overtime made visible', text: 'Make extra hours visible per employee and team. Base decisions on overview instead of loose lists.' },
  { icon: Users, title: 'Staffing per shift', text: 'See where people are needed and which team has room. Focus attention on the shifts that need it.' },
  { icon: ShieldCheck, title: 'Skills & qualifications', text: 'Look beyond headcount. Factor in the required skills and the validity of qualifications in your planning.' },
  { icon: LayoutGrid, title: 'Positioning per shift', text: 'Assign people to the right installation and position for each shift — with an automatic suggestion that fills as many positions as possible.' },
  { icon: ArrowLeftRight, title: 'Swaps & team transfers', text: 'From a one-off swap between two shifts to a permanent move to another team — always with approval and without gaps in the roster.' },
  { icon: UserPlus, title: 'Arrange replacements', text: 'Invite a replacement for an open shift and let them confirm or decline themselves — no more phoning around.' },
  { icon: LayoutDashboard, title: 'One view per role', text: 'An operational view that takes work off the supervisor’s hands, and a central overview for admins. The relevant information in one place, with configurable permissions per role.' },
];
const faqs = [
  ['Which organizations is PetroShift for?', 'For industrial organizations that work with shift teams, such as process industry, energy, chemicals, terminals and manufacturing. The focus is on the coherence between planning, staffing and qualifications.'],
  ['Can PetroShift fit our shift system?', 'Yes. PetroShift isn’t locked into one pattern like 2-2-2 — any shift pattern (for example 4- or 5-team shift systems, or your own cycle) can be set up, including on-call days. Your shift cycle, staffing requirements and agreements are the starting point; in a demo we discuss how your situation translates into PetroShift’s setup.'],
  ['What do supervisors and admins see?', 'The intended role split gives supervisors insight into their operational planning and requests. Admins get an overarching view and manage the setup. We align the exact access and responsibilities with your organization.'],
  ['Is there already an integration with Workday?', 'No, there is no live integration with Workday and data isn’t exchanged automatically. PetroShift does offer a reconciliation step: HR can compare data from PetroShift against Workday and flag discrepancies. A technical integration would need to be researched and agreed on separately.'],
  ['What about security and personal data?', 'An implementation requires establishing access rights, hosting, retention periods, logging and data processing agreements, among other things. We discuss these requirements with your IT and privacy team beforehand. This page does not claim any certifications or specific security guarantees.'],
  ['How do we get started, and what does PetroShift cost?', 'We start with a conversation about your teams, processes and required functionality. Based on that, scope, any integrations, implementation and price can be determined. This page does not offer fixed rates.'],
];

function Logo({ small = false }: { small?: boolean }) { return <span className={`logo supplied-logo ${small ? 'small' : ''}`}><img src="/petroshift-logo.png" alt="PetroShift" width="1448" height="1086" /></span>; }

export default function Home() {
  const [menu, setMenu] = useState(false);
  const [view, setView] = useState('planning');
  const EMPTY_REQUEST = { name: '', company: '', email: '', phone: '', message: '', website: '' };
  const [request, setRequest] = useState(EMPTY_REQUEST);
  const [status, setStatus] = useState<'idle' | 'sending' | 'sent' | 'error'>('idle');
  const demoUrl = (process.env.NEXT_PUBLIC_DEMO_URL || 'https://app.petroshift.nl').trim();
  const email = (process.env.NEXT_PUBLIC_CONTACT_EMAIL || 'info@petroshift.nl').trim();
  const bookingUrl = demoUrl && /^https:\/\//i.test(demoUrl) ? demoUrl : undefined;
  const contactEmail = (email && /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email) ? email : undefined) || 'info@petroshift.nl';
  const field = (key: keyof typeof request) => ({
    value: request[key],
    onChange: (e: ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => setRequest({ ...request, [key]: e.target.value }),
  });
  const sendRequest = async (e: FormEvent) => {
    e.preventDefault();
    setStatus('sending');
    try {
      const res = await fetch('/api/aanvraag', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ naam: request.name, bedrijf: request.company, email: request.email, telefoon: request.phone, bericht: request.message, website: request.website, locale: 'en' }),
      });
      const data = await res.json().catch(() => ({ ok: false }));
      if (!res.ok || !data.ok) throw new Error(data.error || 'Sending failed');
      setStatus('sent');
      setRequest(EMPTY_REQUEST);
    } catch {
      setStatus('error');
    }
  };
  return <>
    <a className="skip-link" href="#main">Skip to content</a>
    <header className="header"><div className="nav-wrap"><a href="#" aria-label="PetroShift homepage"><Logo/></a><nav className={menu?'nav open':'nav'} aria-label="Main navigation" id="main-navigation">{[['Platform','#platform'],['Who it’s for','#who'],['Integrations','#integrations'],['FAQ','#faq'],['Contact','#demo'],['Open the app','https://app.petroshift.nl']].map(([label,href])=><a key={href} href={href} onClick={()=>setMenu(false)}>{label}</a>)}<a href="/" className="lang-switch">NL</a></nav><a href={bookingUrl || "#demo"} className="button nav-cta">View the demo <ArrowUpRight size={17}/></a><button className="menu-toggle" aria-label={menu?'Close menu':'Open menu'} aria-expanded={menu} aria-controls="main-navigation" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div></header>
    <main id="main"><section className="hero"><div className="hero-grid" aria-hidden="true"/><div className="container hero-inner"><div className="eyebrow"><span className="tiny-line"/> BUILT FOR CONTINUOUS OPERATIONS</div><div className="hero-copy"><h1>Grip on every<br/><span>shift.</span></h1><div className="hero-aside"><p>The right people. The right skills.<br/>Every shift, again.</p><p className="muted">From planning and leave to staffing and qualifications. One central overview for teams that keep operations running.</p><div className="hero-actions"><a href={bookingUrl || "#demo"} className="button">Try the demo <ArrowUpRight size={18}/></a><a href="#platform" className="text-link">View the platform <ArrowRight size={17}/></a></div></div></div>
    <div className="product-preview"><div className="preview-caption"><span><span className="orange-square"/> THE OPERATION IN ONE VIEW</span><span>PRODUCT PREVIEW <span className="caption-separator">/</span> 01</span></div><a className="actual-app-preview" href="/petroshift-rooster.png" target="_blank" rel="noopener noreferrer" aria-label="View the full PetroShift roster screenshot in a new tab"><img src="/petroshift-rooster.png" alt="PetroShift roster: monthly matrix for September 2026 with employees, morning, afternoon and night shifts, leave, staffing and shortages." width="1655" height="1275" /><span>View full size <ArrowUpRight size={16}/></span></a><p className="preview-note">This example shows a 5-team 2-2-2 roster — other shift patterns and on-call days are supported just as well.</p></div>
    <div className="hero-bottom"><span>Built for a workday that never stops.</span><div><span>24/7 OPERATIONS</span><span>MULTIPLE TEAMS</span><span>ONE OVERVIEW</span><span>APP COMING SOON TO APP STORE & GOOGLE PLAY</span></div></div></div></section>
    <section className="sector-strip" aria-label="Sectors"><div className="container"><span>WHERE CONTINUITY MATTERS</span><div><span><Factory size={18}/> Process industry</span><span><Layers3 size={18}/> Chemicals & energy</span><span><Cable size={18}/> Terminals & logistics</span><span><SlidersHorizontal size={18}/> Manufacturing</span></div></div></section>
    <section className="section problem" id="solution"><div className="container problem-grid"><div><div className="eyebrow">01 / FROM COMPLEXITY TO CONTROL</div><h2>Operations don’t stop.<br/><span>Your planning has to keep up.</span></h2><p className="section-intro">A sick day. A leave request. An expiring qualification. One change can affect the whole team.</p></div><div className="problem-right"><p>When your planning is spread across spreadsheets, messages and separate systems, you lose the full picture. PetroShift brings together the information you need to act.</p><div className="before-after"><div><span className="before-label">FRAGMENTED</span><span>Rosters in spreadsheets</span><span>Leave via separate messages</span><span>Skills in separate overviews</span></div><ArrowRight size={22}/><div><span className="after-label">CONNECTED</span><span><Check size={16}/> One up-to-date planning view</span><span><Check size={16}/> Requests in context</span><span><Check size={16}/> People and qualifications</span></div></div></div></div></section>
    <section className="section platform" id="platform"><div className="container"><div className="section-head"><div><div className="eyebrow">02 / THE PLATFORM</div><h2>Everything around your team.<br/><span>Nothing falls through the cracks.</span></h2></div><p>From the first roster change to the full picture for the supervisor. More coherence in every decision.</p></div><div className="features">{features.map(({icon:Icon,title,text},i)=><article className="feature" key={title}><div className="feature-top"><Icon size={23} strokeWidth={1.6}/><span>0{i+1}</span></div><h3>{title}</h3><p>{text}</p></article>)}</div><p className="notif-note"><Bell size={16}/> Automatic notifications via WhatsApp, push (in the app) or email — configurable per employee.</p><p className="notif-note"><Download size={16}/> Reports on absence, leave, overtime and staffing, with CSV export for Excel.</p></div></section>
    <section className="section showcase"><div className="container showcase-grid"><div className="showcase-copy"><div className="eyebrow">03 / FROM INSIGHT TO ACTION</div><h2>See what’s happening.<br/><span>Know where you’re needed.</span></h2><p>Good planning goes beyond a filled roster. Bring availability, staffing and skills together before the next shift starts.</p><div className="view-options" aria-label="Choose a product example">{[{id:'planning',n:'01',title:'Plan with an overview',text:'A recognizable rhythm for every team.'},{id:'bezetting',n:'02',title:'See staffing gaps',text:'Focus on the shift that needs it.'},{id:'skills',n:'03',title:'Look beyond headcount',text:'Factor in the right qualifications.'}].map(t=><button aria-pressed={view===t.id} className={view===t.id?'active':''} key={t.id} onClick={()=>setView(t.id)}><span>{t.n}</span><div><strong>{t.title}</strong><small>{t.text}</small></div><ArrowUpRight size={18}/></button>)}</div></div><div className="focus-mockup"><div className="mockup-top"><Logo small/><span>SUPERVISOR VIEW</span></div><span className="mini-eyebrow">{view==='planning'?'REQUESTS':view==='bezetting'?'STAFFING':'QUALIFICATIONS'} / TODAY</span><h3>{view==='planning'?'Leave, with the full picture.':view==='bezetting'?'The next shift, prepared.':'Make skills part of your plan.'}</h3><div className="request-card"><div className="request-person"><span className="person-avatar a1">SB</span><div><strong>{view==='planning'?'Sanne Bakker':view==='bezetting'?'Team B · Late shift':'Working at height'}</strong><small>{view==='planning'?'Field operator · Team B':view==='bezetting'?'14:00 – 22:00 · Plant Rotterdam':'Qualification overview · Plant Rotterdam'}</small></div><span className="pending">{view==='planning'?'Pending':'Needs attention'}</span></div><div className="request-data"><span>{view==='planning'?'Requested leave':view==='bezetting'?'Scheduled / required':'Expiring soon'}<strong>{view==='planning'?'September 18, 2026':view==='bezetting'?'13 / 14 employees':'2 qualifications'}</strong></span><CalendarDays size={24}/></div><div className="check-line"><CheckCircle2 size={17}/><span>{view==='skills'?'18 employees qualified':'Availability in view'}</span></div><div className="check-line"><CheckCircle2 size={17}/><span>{view==='skills'?'Validity per employee':'Team skills visible'}</span></div><div className="review-note"><AlertTriangle size={17}/><span>{view==='planning'?'Check the impact on the late shift before approving.':view==='bezetting'?'Check replacement for the open position.':'Schedule a review or recertification in time.'}</span></div></div><div className="mockup-foot"><span className="orange-square"/> INSIGHT BEFORE YOU DECIDE <span>Illustrative product mockup</span></div></div></div></section>
    <section className="section audience" id="who"><div className="container"><div className="section-head"><div><div className="eyebrow">04 / FOR THE PEOPLE BEHIND THE OPERATION</div><h2>Same operation.<br/><span>Each their own view.</span></h2></div><p>From the shop floor to central management. With information that matches the responsibility.</p></div><div className="roles">{[{n:'01',role:'Supervisors',title:'Calm in day-to-day operations.',text:'Oversee the team, review requests and stay on top of changes before the shift starts — less manual digging, more time for the team.',tags:'Team overview / Requests / Staffing / Less workload'},{n:'02',role:'Planners & operations',title:'Looking ahead with the full picture.',text:'Bring rosters, availability and skills together. Spot bottlenecks and align planning across teams.',tags:'Shift planning / Capacity / Skills'},{n:'03',role:'Admins & HR',title:'Coherence in management.',text:'Connect operational needs with employee data, roles and a consistent setup.',tags:'Management / Roles / HR alignment'}].map(r=><article key={r.n}><span className="role-num">{r.n}</span><span className="role-label">{r.role}</span><h3>{r.title}</h3><p>{r.text}</p><div>{r.tags}</div></article>)}</div></div></section>
    <section className="founder-strip" aria-label="About the founder"><div className="container founder-strip-inner"><img src="/jurrien-bolland.jpg" alt="Jurrien Bolland, founder and owner of PetroShift" width="96" height="96"/><div><span className="founder-role">FOUNDER & OWNER</span><h3>Jurrien Bolland</h3><p>Direct contact with the person building PetroShift — no call center between you and the answers.</p></div></div></section>
    <section className="section integrations" id="integrations"><div className="container integration-grid"><div><div className="eyebrow">05 / FITTING YOUR LANDSCAPE</div><h2>The shop floor and HR.<br/><span>Better connected.</span></h2><p className="section-intro">Your planning doesn’t stand alone. We discuss how PetroShift can connect with your existing processes and systems.</p><div className="security-note"><ShieldCheck size={24}/><div><h3>Security as an implementation requirement</h3><p>We align access, data processing and management with your IT and privacy team beforehand.</p></div></div></div><div className="integration-card"><div className="connection"><Logo small/><FileCheck2 size={26}/><span className="workday">workday<span/></span></div><div className="status-outline">NO LIVE INTEGRATION</div><h3>Workday check for HR</h3><p>PetroShift doesn’t exchange data with Workday automatically. Instead, it’s a reconciliation step: HR compares staffing and hours from PetroShift against Workday and flags discrepancies, without a technical integration.</p><div className="integration-foot"><CircleHelp size={16}/> Manual check, no automatic sync</div></div></div></section>
    <section className="section faq" id="faq"><div className="container faq-grid"><div><div className="eyebrow">06 / GOOD TO KNOW</div><h2>Clear questions.<br/><span>Clear answers.</span></h2><p>A different question? Bring it into the conversation about your operation.</p><a href={bookingUrl || "#demo"} className="text-link">Let’s talk <ArrowUpRight size={18}/></a></div><div className="faq-list">{faqs.map(([q,a])=><details key={q}><summary>{q}<Plus size={19}/></summary><p>{a}</p></details>)}</div></div></section>
    <section className="demo-section" id="demo"><div className="container demo-grid"><div><div className="eyebrow">THE NEXT SHIFT STARTS WITH AN OVERVIEW</div><h2>Ready for more grip<br/>on your operation?</h2><p>See how PetroShift can fit your teams, processes and daily practice.</p><div className="contact-methods"><a href={PHONE_HREF}><Phone size={18}/> {PHONE_DISPLAY}</a><a href={`mailto:${contactEmail}`}><Mail size={18}/> {contactEmail}</a></div><div className="demo-checks"><span><Check size={16}/> Your shift system at the center</span><span><Check size={16}/> Room for in-depth questions</span></div>{bookingUrl && <a className="button button-dark" href={bookingUrl} target="_blank" rel="noopener noreferrer" style={{marginTop:24}}>View the demo <ArrowUpRight size={20}/></a>}</div><form className="aanvraag-form" onSubmit={sendRequest} aria-label="Contact form">{status==='sent'?<><h3>Request sent</h3><p className="form-hint">Thanks — we’ll be in touch as soon as possible.</p></>:<><h3>Request information, no strings attached</h3><p className="form-hint">We’ll get back to you as soon as possible.</p>{status==='error'&&<p className="form-error">Something went wrong. Call or email us directly: <a href={PHONE_HREF}>{PHONE_DISPLAY}</a> or <a href={`mailto:${contactEmail}`}>{contactEmail}</a>.</p>}<div className="field-row"><label>Name*<input required {...field('name')} autoComplete="name"/></label><label>Company<input {...field('company')} autoComplete="organization"/></label></div><div className="field-row"><label>Email*<input required type="email" {...field('email')} autoComplete="email"/></label><label>Phone number<input type="tel" {...field('phone')} autoComplete="tel" placeholder="06 12 34 56 78"/></label></div><label>Message<textarea rows={4} {...field('message')} placeholder="Tell us briefly about your teams and what you need help with."/></label><input className="hp-field" tabIndex={-1} aria-hidden="true" autoComplete="off" {...field('website')}/><button type="submit" className="button button-dark" disabled={status==='sending'}>{status==='sending'?'Sending…':<>Send request <ArrowUpRight size={18}/></>}</button></>}</form></div></section>
    </main><footer><div className="container footer-main"><a href="#" aria-label="PetroShift top"><Logo/></a><p>Built for the people<br/>who keep operations running.</p><a href="#platform">Platform</a><a href="#integrations">Integrations & security</a><a href={bookingUrl || "#demo"}>Demo</a><a href="https://app.petroshift.nl">Open the app</a><a href="/en/privacy">Privacy</a><a href={`mailto:${contactEmail}`}>{contactEmail}</a><a className="footer-phone" href={PHONE_HREF}>{PHONE_DISPLAY}</a></div><div className="container footer-bottom"><span>© {new Date().getFullYear()} PetroShift</span><span>Roster screenshot from the app; other examples are illustrative.</span><span>CONTINUITY, PLANNED.</span></div></footer>
  </>;
}
